#!/usr/bin/env sh
# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# general space settings
yabai -m config layout                       bsp
#yabai -m config top_padding                  26
yabai -m config top_padding                  0
yabai -m config bottom_padding               26
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
echo "yabai configuration loaded.."
