#!/usr/bin/env sh
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                off
#yabai -m config active_window_border_color   0xff555555
#yabai -m config insert_feedback_color       0xff555555
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
#yabai -m config bottom_padding               26
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m rule --add app="^Steam$" manage=off

echo "yabai configuration loaded.."
